//
// Created by meked on 28/10/2025.
//

#ifndef CLASESPROGRAMACIONDINAMICA_DATOSDELALUMNO_H
#define CLASESPROGRAMACIONDINAMICA_DATOSDELALUMNO_H


class Datosdelalumno {
};


#endif //CLASESPROGRAMACIONDINAMICA_DATOSDELALUMNO_H