//
// Created by meked on 28/10/2025.
//

#ifndef CLASESPROGRAMACIONDINAMICA_EJERCICIOPROMEDIO_H
#define CLASESPROGRAMACIONDINAMICA_EJERCICIOPROMEDIO_H


class EjercicioPromedio {
};


#endif //CLASESPROGRAMACIONDINAMICA_EJERCICIOPROMEDIO_H